### PR TITLE
Emglken update for a filesystem bug

### LINKED ISSUE #122: Counterfeit Monkey only starts with Quixe
We have discussed this on the Intfiction.org forum, but I figured it wouldn't hurt to have an issue here as well, so that we don't forget.

The relevant posts are https://intfiction.org/t/lectrote-1-3-6/46539/12 and https://intfiction.org/t/suppressing-line-break-after-cancelling-line-event/13488/8 at the time of writing.

> Under Lectrote-Glulxe it crashes saying “OOM” (abortOnCannotGrowMemory). Under Lectrote-Git it just doesn’t start up – no error message, which is odd, but leaves me no strings to pull.

> In Lectrote 1.3.3, it is possible to get to the initial question (“Can you hear me?”) in Lectrote-Git by compiling Counterfeit Monkey without Startup Precomputation support. However, it is not possible to actually enter an answer, as pressing the enter key has no effect. In 1.3.4 and later, it won’t even start.

It is a little cumbersome to remove Startup Precomptuation from Counterfeit Monkey, so I've uploaded a binary without it here: https://github.com/i7/counterfeit-monkey/releases/tag/r9b7

### PR DESCRIPTION
**Pull request by curiousdannii**
Should fix #122

### CODE REVIEW

**Comment by angstsmurf** [comment]
Yep, seems to work!

**Comment by angstsmurf** [comment]
Hm, when I package Lectrote, I get 
```
file_fopen: failed to open Counterfeit Monkey-startup-data.glkdata: Error: EACCES: permission denied, open 'Counterfeit Monkey-startup-data.glkdata'
```
And the game won't start.

**Comment by curiousdannii** [comment]
MacOS? I have no idea about that, or why it would be different running from source than from packaged.

**Comment by angstsmurf** [comment]
Yeah, it seems the packaged application does not have read access to the file. But it is unclear exactly from where it is trying to open the file, or if it has the right path. You'd think that all applications would have access to their own ~/Library/Application Support/ folder

**Comment by erkyrath** [comment]
I'll take a look later.

**Pull request merged**
