### PR TITLE
Set app name and icon.

### PR DESCRIPTION
**Pull request by RedHatter**
This pull request does two things.

1. Starts lectrote with `electron .` instead of pointing to `main.js` directly.
This was causing electron to bypass the `package.json` and erroneously set the app name as `electron`.

2. Sets the app icon whenever a new window is opened.

### CODE REVIEW

**Comment by erkyrath** [comment]
I've pulled in the change with `electron .` -- thanks. 

I'm not sure about using icon-128.png as a window icon. On MacOS this isn't used, and on Windows windows inherit the .ico from the .exe file, which is preferable. (Particularly for bound apps, which won't use Lectrote's icon-128 anyway.)

I take it you are using Linux? It might make sense to add the icon field to the window options on Linux only.

**Comment by RedHatter** [comment]
Yes, I use linux (KDE Neon to be exact). Does the current solution have any adverse affects on the other systems or do they simply ignore the it?

Only adding the icon on Linux should work fine.

**Comment by curiousdannii** [comment]
Does Electron let you use svg icons in Linux? That would be preferable.

**Comment by RedHatter** [comment]
I believe linux does support svg app icons but I was unable to get it working with electron.

**Comment by erkyrath** [comment]
The adverse effect would be on Windows. The generic Lectrote .png image shouldn't replace the app-specific .ico image.

I'll set it up on Linux only.

**Pull request closed without merging**
